apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: n8n
  namespace: n8n
spec:
  vaultAuthGlobalRef:
    allowDefault: true
  kubernetes:
    role: n8n-role
    serviceAccount: default
