apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: n8n-postgresql-credentials
  namespace: n8n
spec:
  vaultAuthRef: n8n
  mount: secret
  type: kv-v2
  path: n8n/postgresql
  destination:
    name: n8n-postgresql-credentials
    create: true
  refreshAfter: 1h
