apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  vaultAuthRef: n8n
  mount: secret
  type: kv-v2
  path: n8n/encryption
  destination:
    name: n8n-encryption-key
    create: true
  refreshAfter: 1h
