apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ghost-mail-secret
  namespace: ghost
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: ghost/mail
  destination:
    name: ghost-mail-secret
    create: true
  refreshAfter: 1h
