apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: ghost
  namespace: ghost
spec:
  vaultAuthGlobalRef:
    allowDefault: true
  kubernetes:
    role: ghost-role
    serviceAccount: default
