apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ghost-mariadb-secret
  namespace: ghost
spec:
  vaultAuthRef: ghost
  mount: secret
  type: kv-v2
  path: ghost/mariadb
  destination:
    name: ghost-mariadb-secret
    create: true
  refreshAfter: 1h
